apiVersion: apps/v1
kind: Deployment
metadata:
  name: fat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fat
  template:
    metadata:
      labels:
        app: fat
    spec:
      containers:
      - name: app
        image: nivetha140805/fat-app:latest
        ports:
        - containerPort: 8080