apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription
  template:
    metadata:
      labels:
        app: prescription
    spec:
      containers:
      - name: app
        image: nivetha140805/prescription-app:latest
        ports:
        - containerPort: 8080