apiVersion: v1
kind: Service
metadata:
  name: prescription-service
spec:
  type: NodePort   # Exposes app outside cluster
  selector:
    app: prescription   # MUST match deployment label
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 8080  # Container port
      nodePort: 30007   # External port (browser access)